/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/ExcelExporter.e.vm.java
 */
package com.bfds.ach.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import com.bfds.ach.domain.UserRole;
import com.bfds.ach.web.domain.support.GenericExcelExporter;
import com.bfds.ach.web.faces.ConversationContextScoped;

/**
 * Exports to excel document {@link UserRole} search criteria and result. 
 */
@Named
@ConversationContextScoped
public class UserRoleExcelExporter extends GenericExcelExporter<UserRole> {
    @Inject
    protected UserRoleSearchForm sf;

    public UserRoleExcelExporter() {
        super("userRole_roleName");
    }

    @Override
    protected void fillResultItem(int row, UserRole item) {
        int col = 0;
        setValue(row, col++, item.getRoleName());
    }

    @Override
    public void fillSearchCriteria(int row) {
        useCriteriaSheet();

        setSelector(row++, 0, "userRole_roleName", sf.getRoleNameSelector());
    }
}