/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/GraphLoader.e.vm.java
 */
package com.bfds.ach.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.bfds.ach.domain.UserAccount;
import com.bfds.ach.repository.UserAccountRepository;
import com.bfds.ach.repository.support.EntityGraphLoader;

/**
 * Preloads the {@link UserAccount} associations required by the view layer.
 */
@Named
@Singleton
public class UserAccountGraphLoader extends EntityGraphLoader<UserAccount, Long> {
    // required by cglib to create a proxy around the object as we are using the @Transactional annotation
    protected UserAccountGraphLoader() {
        super();
    }

    @Inject
    public UserAccountGraphLoader(UserAccountRepository userAccountRepository) {
        super(userAccountRepository);
    }

    @Override
    public void loadGraph(UserAccount userAccount) {
        loadCollection(userAccount.getRoles());
    }
}