/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/ExcelExporter.e.vm.java
 */
package com.bfds.ach.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import com.bfds.ach.domain.UserAccount;
import com.bfds.ach.web.domain.support.GenericExcelExporter;
import com.bfds.ach.web.faces.ConversationContextScoped;

/**
 * Exports to excel document {@link UserAccount} search criteria and result. 
 */
@Named
@ConversationContextScoped
public class UserAccountExcelExporter extends GenericExcelExporter<UserAccount> {
    @Inject
    protected UserAccountSearchForm sf;

    public UserAccountExcelExporter() {
        super("userAccount_password", //
                "userAccount_userName");
    }

    @Override
    protected void fillResultItem(int row, UserAccount item) {
        int col = 0;
        setValue(row, col++, item.getPassword());
        setValue(row, col++, item.getUserName());
    }

    @Override
    public void fillSearchCriteria(int row) {
        useCriteriaSheet();

        setSelector(row++, 0, "userAccount_password", sf.getPasswordSelector());
        setSelector(row++, 0, "userAccount_userName", sf.getUserNameSelector());
        setSelectedEntities(row++, 0, "userAccount_roles", sf.getUserAccount().getRoles());
    }
}