/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package com.bfds.ach.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.bfds.ach.domain.UserRole;
import com.bfds.ach.printer.UserRolePrinter;
import com.bfds.ach.repository.UserRoleRepository;
import com.bfds.ach.web.domain.support.GenericController;
import com.bfds.ach.web.permission.UserRolePermission;

/**
 * Stateless controller for {@link UserRole} conversation start.
 */
@Named
@Singleton
public class UserRoleController extends GenericController<UserRole, Long> {
    public static final String USERROLE_EDIT_URI = "/domain/userRoleEdit.faces";
    public static final String USERROLE_SELECT_URI = "/domain/userRoleSelect.faces";

    @Inject
    public UserRoleController(UserRoleRepository userRoleRepository, UserRolePermission userRolePermission, UserRolePrinter userRolePrinter) {
        super(userRoleRepository, userRolePermission, userRolePrinter, USERROLE_SELECT_URI, USERROLE_EDIT_URI);
    }
}