/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package com.bfds.ach.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.bfds.ach.domain.UserAccount;
import com.bfds.ach.printer.UserAccountPrinter;
import com.bfds.ach.repository.UserAccountRepository;
import com.bfds.ach.web.domain.support.GenericController;
import com.bfds.ach.web.permission.UserAccountPermission;

/**
 * Stateless controller for {@link UserAccount} conversation start.
 */
@Named
@Singleton
public class UserAccountController extends GenericController<UserAccount, Long> {
    public static final String USERACCOUNT_EDIT_URI = "/domain/userAccountEdit.faces";
    public static final String USERACCOUNT_SELECT_URI = "/domain/userAccountSelect.faces";

    @Inject
    public UserAccountController(UserAccountRepository userAccountRepository, UserAccountPermission userAccountPermission, UserAccountPrinter userAccountPrinter) {
        super(userAccountRepository, userAccountPermission, userAccountPrinter, USERACCOUNT_SELECT_URI, USERACCOUNT_EDIT_URI);
    }
}