/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/repository/Repository.e.vm.java
 */
package com.bfds.ach.repository;

import javax.inject.Named;
import javax.inject.Singleton;

import com.bfds.ach.domain.UserRole;
import com.bfds.ach.repository.support.GenericRepository;

/**
 * {@link GenericRepository} for {@link UserRole} 
 */
@Named
@Singleton
public class UserRoleRepository extends GenericRepository<UserRole, Long> {

    public UserRoleRepository() {
        super(UserRole.class);
    }

    @Override
    public UserRole getNew() {
        return new UserRole();
    }

    @Override
    public UserRole getNewWithDefaults() {
        return getNew().withDefaults();
    }
}