/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 */
package com.bfds.ach.repository;

import javax.inject.Named;
import javax.inject.Singleton;

import com.bfds.ach.domain.UserRole;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@Named
@Singleton
public class UserRoleGenerator {

    /**
     * Returns a new UserRole instance filled with random values.
     */
    public UserRole getUserRole() {
        UserRole userRole = new UserRole();

        // simple attributes follows
        userRole.setRoleName("a");
        return userRole;
    }

}