/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/test/java/service/RepositoryIT.e.vm.java
 */
package com.bfds.ach.repository;

import static com.google.common.collect.Sets.newHashSet;
import static org.fest.assertions.Assertions.assertThat;

import java.util.Set;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.bfds.ach.domain.UserRole;
import com.bfds.ach.repository.UserRoleGenerator;
import com.bfds.ach.repository.UserRoleRepository;

/**
 * Integration test on UserRoleRepository
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class UserRoleRepositoryIT {
    @SuppressWarnings("unused")
    private static final Logger log = LoggerFactory.getLogger(UserRoleRepositoryIT.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Inject
    private UserRoleRepository userRoleRepository;

    @Inject
    private UserRoleGenerator userRoleGenerator;

    @Test
    @Rollback
    public void saveAndGet() {
        UserRole userRole = userRoleGenerator.getUserRole();

        // add it to a Set before saving (force equals/hashcode)
        Set<UserRole> set = newHashSet(userRole, userRole);
        assertThat(set).hasSize(1);

        userRoleRepository.save(userRole);
        entityManager.flush();

        // reload it from cache and check equality
        UserRole model = new UserRole();
        model.setId(userRole.getId());
        assertThat(userRole).isEqualTo(userRoleRepository.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // pk are equals...
        assertThat(userRole.getId()).isEqualTo(userRoleRepository.get(model).getId());

        // but since you do not use a business key, equality is lost.
        assertThat(userRole).isNotEqualTo(userRoleRepository.get(model));
    }
}