/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/printer/Printer.e.vm.java
 */
package com.bfds.ach.printer;

import java.util.Locale;

import javax.inject.Named;
import javax.inject.Singleton;

import com.bfds.ach.domain.UserAccount;
import com.bfds.ach.domain.UserAccount_;
import com.bfds.ach.printer.support.GenericPrinter;

/**
 * {@link GenericPrinter} for {@link UserAccount} 
 *
 * @see TypeAwarePrinter
 */
@Named
@Singleton
public class UserAccountPrinter extends GenericPrinter<UserAccount> {
    public UserAccountPrinter() {
        super(UserAccount.class, UserAccount_.userName.getName());
    }

    @Override
    public String print(UserAccount userAccount, Locale locale) {
        if (userAccount == null) {
            return "";
        }
        StringBuilder ret = new StringBuilder();
        appendIfNotEmpty(ret, userAccount.getUserName());
        return ret.toString();
    }
}