/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/printer/Printer.e.vm.java
 */
package com.bfds.ach.printer;

import java.util.Locale;

import javax.inject.Named;
import javax.inject.Singleton;

import com.bfds.ach.domain.UserRole;
import com.bfds.ach.domain.UserRole_;
import com.bfds.ach.printer.support.GenericPrinter;

/**
 * {@link GenericPrinter} for {@link UserRole} 
 *
 * @see TypeAwarePrinter
 */
@Named
@Singleton
public class UserRolePrinter extends GenericPrinter<UserRole> {
    public UserRolePrinter() {
        super(UserRole.class, UserRole_.roleName.getName());
    }

    @Override
    public String print(UserRole userRole, Locale locale) {
        if (userRole == null) {
            return "";
        }
        StringBuilder ret = new StringBuilder();
        appendIfNotEmpty(ret, userRole.getRoleName());
        return ret.toString();
    }
}